<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bio extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bio_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $bio = $this->Bio_model->get_all();

        $data = array(
            'bio_data' => $bio
        );

        $this->template->load('template','bio_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Bio_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'bio' => $row->bio,
	    );
            $this->template->load('template','bio_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bio'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('bio/create_action'),
	    'id' => set_value('id'),
	    'bio' => set_value('bio'),
	);
        $this->template->load('template','bio_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'bio' => $this->input->post('bio',TRUE),
	    );

            $this->Bio_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bio'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Bio_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('bio/update_action'),
		'id' => set_value('id', $row->id),
		'bio' => set_value('bio', $row->bio),
	    );
            $this->template->load('template','bio_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bio'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'bio' => $this->input->post('bio',TRUE),
	    );

            $this->Bio_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bio'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Bio_model->get_by_id($id);

        if ($row) {
            $this->Bio_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bio'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bio'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('bio', 'bio', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "bio.xls";
        $judul = "bio";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "Bio");

	foreach ($this->Bio_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->bio);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=bio.doc");

        $data = array(
            'bio_data' => $this->Bio_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('bio_doc',$data);
    }

}

/* End of file Jurusan.php */
/* Location: ./application/controllers/Jurusan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-02 03:14:33 */
/* http://harviacode.com */